import { describe, expect, it } from "vitest";

import type {
  ArticleContext,
  DownloadCandidate,
  PaperMetadata,
} from "@papername/core";

import { decideDownload, type ExtensionSettings } from "../src/decision";
import { attachTrustedViewerUrl } from "../src/viewer";

const now = Date.UTC(2026, 8, 4, 12);
const metadata: PaperMetadata = {
  title: "Warm hands, warm heart",
  authors: [
    { name: "Lawrence Williams", familyName: "Williams" },
    { name: "John Bargh", familyName: "Bargh" },
    { name: "Third Author", familyName: "Author" },
  ],
  year: "2008",
  abstract:
    "Holding warm objects led participants to report warmer interpersonal judgments.",
  identifiers: { doi: "10.1126/science.1162548" },
  pdfUrls: ["https://publisher.test/main.pdf"],
};
const context: ArticleContext = {
  metadata,
  pageUrl: "https://publisher.test/article",
  capturedAt: now - 100,
  tabId: 4,
};
const download: DownloadCandidate = {
  url: "https://publisher.test/main.pdf",
  filename: "fulltext.pdf",
  mime: "application/pdf",
  tabId: 4,
  referrer: context.pageUrl,
};
const settings: ExtensionSettings = {
  enabled: true,
  preset: "citation",
  gistConsent: false,
  telemetryEnabled: false,
};

describe("download decision", () => {
  it("renames an Acrobat-mediated arXiv save using the active PDF viewer URL", async () => {
    const arxivContext: ArticleContext = {
      metadata: {
        title:
          "FLY-EVAL++: An Evidence-Driven Evaluation Protocol for Safety-Constrained Flight Prediction with Large Language Models",
        authors: [
          { name: "Wu, Yalun", familyName: "Wu" },
          { name: "Fang, Junfeng", familyName: "Fang" },
          { name: "Wang, Jiawei", familyName: "Wang" },
        ],
        year: "2026",
        identifiers: { arxivId: "2609.04021" },
        pdfUrls: ["https://arxiv.org/pdf/2609.04021"],
      },
      pageUrl: "https://arxiv.org/abs/2609.04021",
      capturedAt: now - 100,
      tabId: 4,
    };
    const acrobatDownload = attachTrustedViewerUrl(
      {
        url: "chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/",
        filename: "292b7576-a42f-4ef1-87dc-066d96f55a95.pdf",
        mime: "application/pdf",
      },
      "https://arxiv.org/pdf/2609.04021",
    );

    await expect(
      decideDownload({
        contexts: [arxivContext],
        download: acrobatDownload,
        settings,
        now: () => now,
      }),
    ).resolves.toMatchObject({
      suggestion: "Wu et al. (2026).pdf",
      outcome: "renamed",
    });
  });

  it("does not attach active-page evidence to an arbitrary download", () => {
    expect(
      attachTrustedViewerUrl(
        {
          url: "https://unrelated.test/file.pdf",
          filename: "file.pdf",
          mime: "application/pdf",
        },
        "https://arxiv.org/pdf/2609.04021",
      ),
    ).not.toHaveProperty("viewerUrl");
  });

  it("associates a versioned arXiv viewer URL by its identifier", async () => {
    const arxivContext: ArticleContext = {
      metadata: {
        title: "A paper with a versioned viewer URL",
        authors: [{ name: "Yalun Wu", familyName: "Wu" }],
        year: "2026",
        identifiers: { arxivId: "2609.04021" },
        pdfUrls: ["https://arxiv.org/pdf/2609.04021"],
      },
      pageUrl: "https://arxiv.org/abs/2609.04021",
      capturedAt: now - 100,
      tabId: 4,
    };
    const acrobatDownload = attachTrustedViewerUrl(
      {
        url: "blob:chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/id",
        filename: "generated-id.pdf",
        mime: "application/pdf",
      },
      "https://arxiv.org/pdf/2609.04021v1",
    );

    await expect(
      decideDownload({
        contexts: [arxivContext],
        download: acrobatDownload,
        settings,
        now: () => now,
      }),
    ).resolves.toMatchObject({ suggestion: "Wu (2026).pdf" });
  });

  it("renames a bioRxiv save generated by Adobe's hosted viewer frame", async () => {
    const biorxivContext: ArticleContext = {
      tabId: 4,
      pageUrl: "https://www.biorxiv.org/content/10.64898/2026.05.08.723731v2",
      capturedAt: now - 100,
      metadata: {
        title:
          "Balance control is more affected in older than younger adults by repeated visual perturbations during walking",
        authors: [
          { name: "Yaqi Li", familyName: "Li" },
          { name: "Eugénie Lambrecht", familyName: "Lambrecht" },
          { name: "Sjoerd M Bruijn", familyName: "Bruijn" },
          { name: "Jaap H. van Dieën", familyName: "Dieën" },
        ],
        year: "2026",
        identifiers: { doi: "10.64898/2026.05.08.723731" },
        pdfUrls: [
          "https://www.biorxiv.org/content/biorxiv/early/2026/09/10/2026.05.08.723731.full.pdf",
        ],
        sourceAdapter: "biorxiv",
      },
    };
    const hostedAdobeDownload = attachTrustedViewerUrl(
      {
        url: "blob:https://acrobat.adobe.com/generated-id",
        referrer: "https://acrobat.adobe.com/dc-chrome-extension/index.html",
        filename: "01ae801d-8122-4979-84c8-3d2fd609d6b2.pdf",
        mime: "application/pdf",
      },
      "https://www.biorxiv.org/content/10.64898/2026.05.08.723731v2.full.pdf",
    );

    await expect(
      decideDownload({
        contexts: [biorxivContext],
        download: hostedAdobeDownload,
        settings,
        now: () => now,
      }),
    ).resolves.toMatchObject({
      suggestion: "Li et al. (2026).pdf",
      outcome: "renamed",
    });
  });

  it("renames Research Square's redirected UUID asset", async () => {
    const researchSquareContext: ArticleContext = {
      tabId: 4,
      pageUrl: "https://www.researchsquare.com/article/rs-10663751/v1",
      capturedAt: now - 100,
      metadata: {
        title: "Risk factors for drug-resistant tuberculosis",
        authors: [
          { name: "Mathias Ngobi Bogere", familyName: "Bogere" },
          { name: "Maxwell Otim Onapa", familyName: "Onapa" },
          { name: "Jimmy Patrick Alunyo", familyName: "Alunyo" },
        ],
        year: "2026",
        identifiers: { doi: "10.21203/rs.3.rs-10663751/v1" },
        pdfUrls: [
          "https://www.researchsquare.com/article/rs-10663751/v1.pdf?c=1789058428000",
        ],
        sourceAdapter: "research-square",
      },
    };
    const hostedAdobeDownload = attachTrustedViewerUrl(
      {
        url: "blob:https://acrobat.adobe.com/generated-id",
        referrer: "https://acrobat.adobe.com/dc-chrome-extension/index.html",
        filename: "2f163bbe-f47b-44cb-a70d-e0375c11d07f.pdf",
        mime: "application/pdf",
      },
      "https://assets-eu.researchsquare.com/files/rs-10663751/v1/a34f7bb0-d42f-4afd-a2a3-5c2c16203f13.pdf?c=1789044028",
    );

    await expect(
      decideDownload({
        contexts: [researchSquareContext],
        download: hostedAdobeDownload,
        settings,
        now: () => now,
      }),
    ).resolves.toMatchObject({
      suggestion: "Bogere et al. (2026).pdf",
      outcome: "renamed",
    });
  });

  it("returns the selected deterministic filename for an eligible download", async () => {
    await expect(
      decideDownload({
        contexts: [context],
        download,
        settings,
        now: () => now,
      }),
    ).resolves.toMatchObject({
      suggestion: "Williams et al. (2008).pdf",
      outcome: "renamed",
      reason: "selected_preset",
    });
  });

  it("renames an OSF primary-file download captured from the MFR viewer", async () => {
    const osfPdfUrl = "https://osf.io/download/6aa17d8ca9afb7bc95af9441/";
    const osfContext: ArticleContext = {
      tabId: 4,
      pageUrl: "https://osf.io/preprints/psyarxiv/qmh3s_v3",
      capturedAt: now - 100,
      metadata: {
        title:
          "Artificial Intelligence Systems Distort Upstream Selection in Human Social Learning",
        authors: [
          { name: "William J. Brady", familyName: "Brady" },
          { name: "Chen-Wei Yu", familyName: "Yu" },
          { name: "Nicholas Ornstein", familyName: "Ornstein" },
          { name: "Bolun Sun", familyName: "Sun" },
          { name: "Joshua Conrad Jackson", familyName: "Jackson" },
        ],
        year: "2026",
        identifiers: { doi: "10.31234/osf.io/qmh3s_v3" },
        pdfUrls: [osfPdfUrl],
        sourceAdapter: "osf",
      },
    };

    await expect(
      decideDownload({
        contexts: [osfContext],
        download: {
          url: `${osfPdfUrl}?direct&mode=render`,
          finalUrl:
            "https://files.osf.io/v1/resources/qmh3s/providers/osfstorage/file",
          filename: "Clean_Bradyetal_SelectionProblem_Manuscript_preprint.pdf",
          mime: "application/pdf",
        },
        settings,
        now: () => now,
      }),
    ).resolves.toMatchObject({
      suggestion: "Brady et al. (2026).pdf",
      outcome: "renamed",
    });
  });

  it("renames the signed Google Storage download returned by OSF", async () => {
    const osfPdfUrl = "https://osf.io/download/6aa17d8ca9afb7bc95af9441/";
    const osfContext: ArticleContext = {
      tabId: 4,
      pageUrl: "https://osf.io/preprints/psyarxiv/qmh3s_v3",
      capturedAt: now - 100,
      metadata: {
        title:
          "Artificial Intelligence Systems Distort Upstream Selection in Human Social Learning",
        authors: [
          { name: "William J. Brady", familyName: "Brady" },
          { name: "Chen-Wei Yu", familyName: "Yu" },
          { name: "Nicholas Ornstein", familyName: "Ornstein" },
        ],
        year: "2026",
        identifiers: { doi: "10.31234/osf.io/qmh3s_v3" },
        pdfUrls: [osfPdfUrl],
        sourceAdapter: "osf",
      },
    };
    const signedUrl =
      "https://storage.googleapis.com/cos-osf-prod-files-us-east1/2263de65d54d3f0537cf6ab7370689e1b752ba2f62c61092017578518b6fab5f?response-content-disposition=attachment%3B%20filename%3D%22Clean_Bradyetal_SelectionProblem_Manuscript_preprint.pdf%22&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789091190&Signature=redacted";

    await expect(
      decideDownload({
        contexts: [osfContext],
        download: {
          url: signedUrl,
          finalUrl: signedUrl,
          referrer: "https://osf.io/",
          filename: "Clean_Bradyetal_SelectionProblem_Manuscript_preprint.pdf",
          mime: "application/pdf",
        },
        settings,
        now: () => now,
      }),
    ).resolves.toMatchObject({
      suggestion: "Brady et al. (2026).pdf",
      outcome: "renamed",
    });
  });

  it("renames a proxied PDF using its selected Google Scholar result", async () => {
    const proxyPdf =
      "https://link-springer-com.proxy.library.edu/content/pdf/10.1007/example.pdf";
    await expect(
      decideDownload({
        contexts: [
          {
            tabId: 8,
            pageUrl: "https://scholar.google.com/scholar?q=human+agency",
            capturedAt: now - 100,
            metadata: {
              title: "Subjective quantitative studies of human agency",
              authors: [{ name: "S Alkire", familyName: "Alkire" }],
              year: "2005",
              identifiers: { doi: "10.1007/example" },
              pdfUrls: [proxyPdf],
              sourceAdapter: "google-scholar",
            },
          },
        ],
        download: {
          url: "https://link.springer.com/content/pdf/10.1007/example.pdf",
          filename: "10.1007-example.pdf",
          mime: "application/pdf",
        },
        settings,
        now: () => now,
      }),
    ).resolves.toMatchObject({
      suggestion: "Alkire (2005).pdf",
      outcome: "renamed",
    });
  });

  it("does nothing when Papername is disabled or the PDF is unrelated", async () => {
    await expect(
      decideDownload({
        contexts: [context],
        download,
        settings: { ...settings, enabled: false },
        now: () => now,
      }),
    ).resolves.toEqual({ outcome: "unchanged", reason: "disabled" });
    await expect(
      decideDownload({
        contexts: [context],
        download: {
          ...download,
          url: "https://other.test/file.pdf",
          tabId: 8,
          referrer: "",
        },
        settings,
        now: () => now,
      }),
    ).resolves.toEqual({ outcome: "unchanged", reason: "unmatched_download" });
  });

  it("uses a hosted gist when it arrives within the wait budget", async () => {
    await expect(
      decideDownload({
        contexts: [context],
        download,
        settings: {
          ...settings,
          preset: "citation_gist",
          gistConsent: true,
          betaToken: "token",
        },
        requestGist: async () => ({
          usable: true,
          gist: "Warm objects increase perceived interpersonal warmth",
          reason: "ok",
          remaining: 29,
        }),
        timeoutMs: 1_500,
        now: () => now,
      }),
    ).resolves.toMatchObject({
      suggestion:
        "Williams et al. (2008) — Warm objects increase perceived interpersonal warmth.pdf",
      outcome: "renamed",
      remaining: 29,
    });
  });

  it("rejects a gist that repeats an author or publication year", async () => {
    const result = await decideDownload({
      contexts: [context],
      download,
      settings: {
        ...settings,
        preset: "citation_gist",
        gistConsent: true,
        betaToken: "token",
      },
      requestGist: async () => ({
        usable: true,
        gist: "Williams 2008 reports warmer judgments from warm objects",
        reason: "ok",
        remaining: 29,
      }),
      now: () => now,
    });

    expect(result).toMatchObject({
      outcome: "fallback",
      reason: "invalid_gist",
      remaining: 29,
    });
  });

  it("compares short author names as whole tokens", async () => {
    const result = await decideDownload({
      contexts: [
        {
          ...context,
          metadata: {
            ...metadata,
            authors: [{ name: "Mei Li", familyName: "Li" }],
          },
        },
      ],
      download,
      settings: {
        ...settings,
        preset: "citation_gist",
        gistConsent: true,
        betaToken: "token",
      },
      requestGist: async () => ({
        usable: true,
        gist: "Climate interventions reduce perceived household energy costs",
        reason: "ok",
        remaining: 29,
      }),
      now: () => now,
    });

    expect(result).toMatchObject({
      outcome: "renamed",
      reason: "selected_preset",
      remaining: 29,
    });
  });

  it("falls back to citation plus title after the wait budget", async () => {
    await expect(
      decideDownload({
        contexts: [context],
        download,
        settings: {
          ...settings,
          preset: "citation_gist",
          gistConsent: true,
          betaToken: "token",
        },
        requestGist: () => new Promise(() => undefined),
        timeoutMs: 5,
        now: () => now,
      }),
    ).resolves.toMatchObject({
      suggestion: "Williams et al. (2008) — Warm hands, warm heart.pdf",
      outcome: "fallback",
      reason: "gist_timeout",
    });
  });

  it("does not call hosted AI without consent or a beta token", async () => {
    let calls = 0;
    const result = await decideDownload({
      contexts: [context],
      download,
      settings: { ...settings, preset: "citation_gist" },
      requestGist: async () => {
        calls += 1;
        throw new Error("must not run");
      },
      now: () => now,
    });
    expect(calls).toBe(0);
    expect(result).toMatchObject({
      outcome: "fallback",
      reason: "gist_unavailable",
    });
  });

  it("does not spend gist quota when no author can appear in the selected format", async () => {
    let calls = 0;
    const result = await decideDownload({
      contexts: [{ ...context, metadata: { ...metadata, authors: [] } }],
      download,
      settings: {
        ...settings,
        preset: "citation_gist",
        gistConsent: true,
        betaToken: "token",
      },
      requestGist: async () => {
        calls += 1;
        throw new Error("must not run");
      },
      now: () => now,
    });

    expect(calls).toBe(0);
    expect(result).toMatchObject({
      suggestion: "Warm hands, warm heart.pdf",
      outcome: "fallback",
      reason: "missing_author",
    });
  });

  it("surfaces a zero remaining allowance when quota is exhausted", async () => {
    const result = await decideDownload({
      contexts: [context],
      download,
      settings: {
        ...settings,
        preset: "citation_gist",
        gistConsent: true,
        betaToken: "token",
      },
      requestGist: async () =>
        Promise.reject(
          Object.assign(new Error("quota exhausted"), {
            reason: "quota_exhausted",
            remaining: 0,
          }),
        ),
      now: () => now,
    });

    expect(result).toMatchObject({
      outcome: "fallback",
      reason: "quota_exhausted",
      remaining: 0,
    });
  });
});
